/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class AnswerInfoDTO 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4936869614995675506L;
    private String type;
    private LinkedHashMap<String, Object> info;
    /** GETTER
     * Answer info type name
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * Answer info type name
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * Answer info details
     */
    @JsonGetter("info")
    public LinkedHashMap<String, Object> getInfo ( ) { 
        return this.info;
    }
    
    /** SETTER
     * Answer info details
     */
    @JsonSetter("info")
    public void setInfo (LinkedHashMap<String, Object> value) { 
        this.info = value;
    }
 
}
