/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ConditionDTO 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8393732686146750473L;
    private String identifier;
    private String title;
    private Integer riskRating;
    private String diagnosis;
    private String explanation;
    private String description;
    private String living;
    private String videoLiving;
    private String iconAbout;
    private String iconRisks;
    private String iconWhatYouCanDo;
    private String videoWhatYouCanDo;
    private String recommendation;
    private List<String> recommendedProductIdentifiers;
    private List<String> relatedProductIdentifiers;
    private String risksHeader;
    private List<String> risks;
    private String benefitsHeader;
    private List<String> benefits;
    private List<String> tipIdentifiers;
    private List<String> tidbitIdentifiers;
    private String whileWaiting;
    private Boolean conditionFeedback;
    /** GETTER
     * The identifier of the condition.
     */
    @JsonGetter("identifier")
    public String getIdentifier ( ) { 
        return this.identifier;
    }
    
    /** SETTER
     * The identifier of the condition.
     */
    @JsonSetter("identifier")
    public void setIdentifier (String value) { 
        this.identifier = value;
    }
 
    /** GETTER
     * The title of the condition.
     */
    @JsonGetter("title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * The title of the condition.
     */
    @JsonSetter("title")
    public void setTitle (String value) { 
        this.title = value;
    }
 
    /** GETTER
     * The risk rating of the condition.
     */
    @JsonGetter("riskRating")
    public Integer getRiskRating ( ) { 
        return this.riskRating;
    }
    
    /** SETTER
     * The risk rating of the condition.
     */
    @JsonSetter("riskRating")
    public void setRiskRating (Integer value) { 
        this.riskRating = value;
    }
 
    /** GETTER
     * The diagnosis of the condition.
     */
    @JsonGetter("diagnosis")
    public String getDiagnosis ( ) { 
        return this.diagnosis;
    }
    
    /** SETTER
     * The diagnosis of the condition.
     */
    @JsonSetter("diagnosis")
    public void setDiagnosis (String value) { 
        this.diagnosis = value;
    }
 
    /** GETTER
     * The explanation of the condition.
     */
    @JsonGetter("explanation")
    public String getExplanation ( ) { 
        return this.explanation;
    }
    
    /** SETTER
     * The explanation of the condition.
     */
    @JsonSetter("explanation")
    public void setExplanation (String value) { 
        this.explanation = value;
    }
 
    /** GETTER
     * The description of the condition.
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * The description of the condition.
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * The living content of the condition.
     */
    @JsonGetter("living")
    public String getLiving ( ) { 
        return this.living;
    }
    
    /** SETTER
     * The living content of the condition.
     */
    @JsonSetter("living")
    public void setLiving (String value) { 
        this.living = value;
    }
 
    /** GETTER
     * The key for the living video.
     */
    @JsonGetter("videoLiving")
    public String getVideoLiving ( ) { 
        return this.videoLiving;
    }
    
    /** SETTER
     * The key for the living video.
     */
    @JsonSetter("videoLiving")
    public void setVideoLiving (String value) { 
        this.videoLiving = value;
    }
 
    /** GETTER
     * The key for the about icon.
     */
    @JsonGetter("iconAbout")
    public String getIconAbout ( ) { 
        return this.iconAbout;
    }
    
    /** SETTER
     * The key for the about icon.
     */
    @JsonSetter("iconAbout")
    public void setIconAbout (String value) { 
        this.iconAbout = value;
    }
 
    /** GETTER
     * The key for the risk icon.
     */
    @JsonGetter("iconRisks")
    public String getIconRisks ( ) { 
        return this.iconRisks;
    }
    
    /** SETTER
     * The key for the risk icon.
     */
    @JsonSetter("iconRisks")
    public void setIconRisks (String value) { 
        this.iconRisks = value;
    }
 
    /** GETTER
     * The key for the what you can do icon.
     */
    @JsonGetter("iconWhatYouCanDo")
    public String getIconWhatYouCanDo ( ) { 
        return this.iconWhatYouCanDo;
    }
    
    /** SETTER
     * The key for the what you can do icon.
     */
    @JsonSetter("iconWhatYouCanDo")
    public void setIconWhatYouCanDo (String value) { 
        this.iconWhatYouCanDo = value;
    }
 
    /** GETTER
     * The key for the what you can do video.
     */
    @JsonGetter("videoWhatYouCanDo")
    public String getVideoWhatYouCanDo ( ) { 
        return this.videoWhatYouCanDo;
    }
    
    /** SETTER
     * The key for the what you can do video.
     */
    @JsonSetter("videoWhatYouCanDo")
    public void setVideoWhatYouCanDo (String value) { 
        this.videoWhatYouCanDo = value;
    }
 
    /** GETTER
     * The recommendation of the condition.
     */
    @JsonGetter("recommendation")
    public String getRecommendation ( ) { 
        return this.recommendation;
    }
    
    /** SETTER
     * The recommendation of the condition.
     */
    @JsonSetter("recommendation")
    public void setRecommendation (String value) { 
        this.recommendation = value;
    }
    
    /** GETTER
     * The recommended product identifiers associated with the condition.
     */
    @JsonGetter("recommendedProductIdentifiers")
    public List<String> getRecommendedProductIdentifiers() {
		return recommendedProductIdentifiers;
	}

    /** SETTER
     * The recommended product identifiers associated with the condition.
     */
    @JsonSetter("recommendedProductIdentifiers")
    public void setRecommendedProductIdentifiers(List<String> value) {
		this.recommendedProductIdentifiers = value;
	}

	/** GETTER
     * The related product identifiers associated with the condition.
     */
    @JsonGetter("relatedProductIdentifiers")
	public List<String> getRelatedProductIdentifiers() {
		return relatedProductIdentifiers;
	}

    /** SETTER
     * The related product identifiers associated with the condition.
     */
    @JsonSetter("relatedProductIdentifiers")
    public void setRelatedProductIdentifiers(List<String> value) {
		this.relatedProductIdentifiers = value;
	}
 
    /** GETTER
     * The risk header of the condition.
     */
    @JsonGetter("risksHeader")
    public String getRisksHeader ( ) { 
        return this.risksHeader;
    }
    
    /** SETTER
     * The risk header of the conditon.
     */
    @JsonSetter("risksHeader")
    public void setRisksHeader (String value) { 
        this.risksHeader = value;
    }
 
    /** GETTER
     * The risks of the condition.
     */
    @JsonGetter("risks")
    public List<String> getRisks ( ) { 
        return this.risks;
    }
    
    /** SETTER
     * The risks of the condition.
     */
    @JsonSetter("risks")
    public void setRisks (List<String> value) { 
        this.risks = value;
    }
 
    /** GETTER
     * The benefits header of the condition.
     */
    @JsonGetter("benefitsHeader")
    public String getBenefitsHeader ( ) { 
        return this.benefitsHeader;
    }
    
    /** SETTER
     * The benefits header of the condition.
     */
    @JsonSetter("benefitsHeader")
    public void setBenefitsHeader (String value) { 
        this.benefitsHeader = value;
    }
 
    /** GETTER
     * The benefits of the condition.
     */
    @JsonGetter("benefits")
    public List<String> getBenefits ( ) { 
        return this.benefits;
    }
    
    /** SETTER
     * The benefits of the condition.
     */
    @JsonSetter("benefits")
    public void setBenefits (List<String> value) { 
        this.benefits = value;
    }
 
    /** GETTER
     * The tip identifiers associated with the condition.
     */
    @JsonGetter("tipIdentifiers")
    public List<String> getTipIdentifiers ( ) { 
        return this.tipIdentifiers;
    }
    
    /** SETTER
     * The tip identifiers associated with the condition.
     */
    @JsonSetter("tipIdentifiers")
    public void setTipIdentifiers (List<String> value) { 
        this.tipIdentifiers = value;
    }
 
    /** GETTER
     * The tidbit identifiers with the condition.
     */
    @JsonGetter("tidbitIdentifiers")
    public List<String> getTidbitIdentifiers ( ) { 
        return this.tidbitIdentifiers;
    }
    
    /** SETTER
     * The tidbit identifiers with the condition.
     */
    @JsonSetter("tidbitIdentifiers")
    public void setTidbitIdentifiers (List<String> value) { 
        this.tidbitIdentifiers = value;
    }
 
    /** GETTER
     * The while waiting content of the condition.
     */
    @JsonGetter("whileWaiting")
    public String getWhileWaiting ( ) { 
        return this.whileWaiting;
    }
    
    /** SETTER
     * The while waiting content of the condition.
     */
    @JsonSetter("whileWaiting")
    public void setWhileWaiting (String value) { 
        this.whileWaiting = value;
    }
 
    /** GETTER
     * The feedback flag indicating whether the end-user agrees with the condition.
     */
    @JsonGetter("conditionFeedback")
    public Boolean getSessionFeedback ( ) {
        return this.conditionFeedback;
    }
    
    /** SETTER
     * The feedback flag indicating whether the end-user agrees with the condition.
     */
    @JsonSetter("conditionFeedback")
    public void setConditionFeedback (Boolean value) {
        this.conditionFeedback = value;
    }
 
}
