/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

public class ProductDTOBuilder {
    //the instance to build
    private ProductDTO productDTO;

    /**
     * Default constructor to initialize the instance
     */
    public ProductDTOBuilder() {
        productDTO = new ProductDTO();
    }

    /**
     * The identifier of the related product.
     */
    public ProductDTOBuilder identifier(String identifier) {
    	productDTO.setIdentifier(identifier);
        return this;
    }

    /**
     * The title of the related product.
     */
    public ProductDTOBuilder title(String title) {
    	productDTO.setTitle(title);
        return this;
    }

    /**
     * The header of the related product.
     */
    public ProductDTOBuilder header(String header) {
        productDTO.setHeader(header);
        return this;
    }

    /**
     * The detail content of the related product.
     */
    public ProductDTOBuilder detail(String detail) {
        productDTO.setDetail(detail);
        return this;
    }
    
    /**
     * The icon key of the related product.
     */
    public ProductDTOBuilder icon(String icon) {
        productDTO.setIcon(icon);
        return this;
    }

    /**
     * The link of the related product.
     */
    public ProductDTOBuilder link(String link) {
        productDTO.setLink(link);
        return this;
    }
    
    /**
     * The TagName of the related product.
     */
    public ProductDTOBuilder tagName(String tagName) {
        productDTO.setTagName(tagName);
        return this;
    }

    /**
     * Build the instance with the given values
     */
    public ProductDTO build() {
        return productDTO;
    }
}
