/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ProductDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6585619993426892918L;
	private String identifier;
    private String title;
    private String header;
    private String detail;
    private String icon;
    private String link;
    private String tagName;
    
    /** GETTER
     * The identifier of the related product.
     */
    @JsonGetter("identifier")
	public String getIdentifier() {
		return identifier;
	}
	
    /** SETTER
     * The identifier of the related product.
     */
    @JsonSetter("identifier")
	public void setIdentifier(String value) {
		this.identifier = value;
	}
	
    /** GETTER
     * The title of the related product.
     */
    @JsonGetter("title")
    public String getTitle() {
		return title;
	}
	
    /** SETTER
     * The title of the related product.
     */
    @JsonSetter("title")
    public void setTitle(String value) {
		this.title = value;
	}
	
	/** GETTER
     * The header of the related product.
     */
    @JsonGetter("header")
	public String getHeader() {
		return header;
	}
	
    /** SETTER
     * The header of the related product.
     */
    @JsonSetter("header")
    public void setHeader(String value) {
		this.header = value;
	}
	
	/** GETTER
     * The detail content of the related product.
     */
    @JsonGetter("detail")
	public String getDetail() {
		return detail;
	}
	
    /** SETTER
     * The detail content of the related product.
     */
    @JsonSetter("detail")
    public void setDetail(String value) {
		this.detail = value;
	}
	
	/** GETTER
     * The icon key of the related product.
     */
    @JsonGetter("icon")
	public String getIcon() {
		return icon;
	}
	
    /** SETTER
     * The icon key of the related product.
     */
    @JsonSetter("icon")
    public void setIcon(String value) {
		this.icon = value;
	}
	
	/** GETTER
     * The link of the related product.
     */
    @JsonGetter("link")
	public String getLink() {
		return link;
	}
	
    /** SETTER
     * The link of the related product.
     */
    @JsonSetter("link")
    public void setLink(String value) {
		this.link = value;
	}

    /** GETTER
     * The TagName of the related product.
     */
    @JsonGetter("tagName")
    public String getTagName() {
		return tagName;
	}

    /** SETTER
     * The TagName of the related product.
     */
    @JsonSetter("tagName")
    public void setTagName(String value) {
		this.tagName = value;
	}
    
}
