/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;

public class QuestionsDTOBuilder {
    //the instance to build
    private QuestionsDTO questionsDTO;

    /**
     * Default constructor to initialize the instance
     */
    public QuestionsDTOBuilder() {
        questionsDTO = new QuestionsDTO();
    }

    /**
     * An answer template for populating, and submitting answers with.
     */
    public QuestionsDTOBuilder answersTemplate(LinkedHashMap<String, Object> answersTemplate) {
        questionsDTO.setAnswersTemplate(answersTemplate);
        return this;
    }

    /**
     * The heading for a set of QuestionDTOs
     */
    public QuestionsDTOBuilder heading(String heading) {
        questionsDTO.setHeading(heading);
        return this;
    }

    /**
     * The QuestionDTO items requested.
     */
    public QuestionsDTOBuilder questions(List<QuestionDTO> questions) {
        questionsDTO.setQuestions(questions);
        return this;
    }

    /**
     * Contains the information necessary to perform a survey update.
     */
    public QuestionsDTOBuilder updateAnswersTemplate(UpdateSurveyStateRequestDTO updateAnswersTemplate) {
        questionsDTO.setUpdateAnswersTemplate(updateAnswersTemplate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public QuestionsDTO build() {
        return questionsDTO;
    }
}