/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;

public class ResultDTOBuilder {
    //the instance to build
    private ResultDTO resultDTO;

    /**
     * Default constructor to initialize the instance
     */
    public ResultDTOBuilder() {
        resultDTO = new ResultDTO();
    }

    /**
     * The conditions identified for the session.
     */
    public ResultDTOBuilder conditions(List<ConditionDTO> conditions) {
        resultDTO.setConditions(conditions);
        return this;
    }

    /**
     * The tips identified for the session.
     */
    public ResultDTOBuilder tips(List<TipDTO> tips) {
        resultDTO.setTips(tips);
        return this;
    }

    /**
     * The tidbits identified for the session.
     */
    public ResultDTOBuilder tidbits(List<TidbitDTO> tidbits) {
        resultDTO.setTidbits(tidbits);
        return this;
    }
    
    /**
     * The related products identified for all conditions.
     */
    public ResultDTOBuilder products(List<ProductDTO> products) {
        resultDTO.setProducts(products);
        return this;
    }

    /**
     * Custom calculations that can be used by the client.
     */
    public ResultDTOBuilder calculations(LinkedHashMap<String, Object> calculations) {
        resultDTO.setCalculations(calculations);
        return this;
    }

    /**
     * The sense values used to generate the result. This is only returned in Development environments.
     */
    public ResultDTOBuilder senseValues(LinkedHashMap<String, Object> senseValues) {
        resultDTO.setSenseValues(senseValues);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ResultDTO build() {
        return resultDTO;
    }
}
