/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class SenseDTO 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8147459747974828473L;
    private String id;
    private String type;
    private Boolean computed;
    private Boolean sleepProblem;
    private List<SenseDependencyDTO> dependencies;
    private String questionText;
    /** GETTER
     * The id of the sense.
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * The id of the sense.
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * The type of the sense.
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The type of the sense.
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * Indicates whether the sense is computed.
     */
    @JsonGetter("computed")
    public Boolean getComputed ( ) { 
        return this.computed;
    }
    
    /** SETTER
     * Indicates whether the sense is computed.
     */
    @JsonSetter("computed")
    public void setComputed (Boolean value) { 
        this.computed = value;
    }
 
    /** GETTER
     * Indicates whether the sense represents a sleep problem.
     */
    @JsonGetter("sleepProblem")
    public Boolean getSleepProblem ( ) { 
        return this.sleepProblem;
    }
    
    /** SETTER
     * Indicates whether the sense represents a sleep problem.
     */
    @JsonSetter("sleepProblem")
    public void setSleepProblem (Boolean value) { 
        this.sleepProblem = value;
    }
 
    /** GETTER
     * Dependency senses used to compute the sense.
     */
    @JsonGetter("dependencies")
    public List<SenseDependencyDTO> getDependencies ( ) { 
        return this.dependencies;
    }
    
    /** SETTER
     * Dependency senses used to compute the sense.
     */
    @JsonSetter("dependencies")
    public void setDependencies (List<SenseDependencyDTO> value) { 
        this.dependencies = value;
    }
 
    /** GETTER
     * Locale specific question text which can be used to ask an end-user for the sense value as a question. Only set for
     * question senses.
     */
    @JsonGetter("questionText")
    public String getQuestionText ( ) { 
        return this.questionText;
    }
    
    /** SETTER
     * Locale specific question text which can be used to ask an end-user for the sense value as a question. Only set for
     * question senses.
     */
    @JsonSetter("questionText")
    public void setQuestionText (String value) { 
        this.questionText = value;
    }
 
}
