/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;

public class SenseDTOBuilder {
    //the instance to build
    private SenseDTO senseDTO;

    /**
     * Default constructor to initialize the instance
     */
    public SenseDTOBuilder() {
        senseDTO = new SenseDTO();
    }

    /**
     * The id of the sense.
     */
    public SenseDTOBuilder id(String id) {
        senseDTO.setId(id);
        return this;
    }

    /**
     * The type of the sense.
     */
    public SenseDTOBuilder type(String type) {
        senseDTO.setType(type);
        return this;
    }

    /**
     * Indicates whether the sense is computed.
     */
    public SenseDTOBuilder computed(Boolean computed) {
        senseDTO.setComputed(computed);
        return this;
    }

    /**
     * Indicates whether the sense represents a sleep problem.
     */
    public SenseDTOBuilder sleepProblem(Boolean sleepProblem) {
        senseDTO.setSleepProblem(sleepProblem);
        return this;
    }

    /**
     * Dependency senses used to compute the sense.
     */
    public SenseDTOBuilder dependencies(List<SenseDependencyDTO> dependencies) {
        senseDTO.setDependencies(dependencies);
        return this;
    }

    /**
     * Locale specific question text which can be used to ask an end-user for the sense value as a question. Only set for
     * question senses.
     */
    public SenseDTOBuilder questionText(String questionText) {
        senseDTO.setQuestionText(questionText);
        return this;
    }
    
    /**
     * Information about the answers expected for any non-computed senses.
     */
    public SenseDTOBuilder answerInfo(AnswerInfoDTO answerInfo) {
        senseDTO.setAnswerInfo(answerInfo);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SenseDTO build() {
        return senseDTO;
    }
}
