/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class StepStateDTO 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5506395160207455977L;
    private String identifier;
    private String sectionRef;
    private List<String> questionRefs;
    private String heading;
    private String renderer;
    /** GETTER
     * The identifier of the step.
     */
    @JsonGetter("identifier")
    public String getIdentifier ( ) { 
        return this.identifier;
    }
    
    /** SETTER
     * The identifier of the step.
     */
    @JsonSetter("identifier")
    public void setIdentifier (String value) { 
        this.identifier = value;
    }
 
    /** GETTER
     * The identifier of the section to which the step belongs.
     */
    @JsonGetter("sectionRef")
    public String getSectionRef ( ) { 
        return this.sectionRef;
    }
    
    /** SETTER
     * The identifier of the section to which the step belongs.
     */
    @JsonSetter("sectionRef")
    public void setSectionRef (String value) { 
        this.sectionRef = value;
    }
    
    /** GETTER
     * The identifier of a custom client renderer used to display the step.
     */
    @JsonGetter("renderer")
    public String getRenderer ( ) { 
        return this.renderer;
    }
    
    /** SETTER
     * The identifier of a custom client renderer used to display the step.
     */
    @JsonSetter("renderer")
    public void setRenderer (String value) { 
        this.renderer = value;
    }
 
    /** GETTER
     * List of question identifiers for questions to be displayed on the step.
     */
    @JsonGetter("questionRefs")
    public List<String> getQuestionRefs ( ) { 
        return this.questionRefs;
    }
    
    /** SETTER
     * List of question identifiers for questions to be displayed on the step.
     */
    @JsonSetter("questionRefs")
    public void setQuestionRefs (List<String> value) { 
        this.questionRefs = value;
    }
 
    /** GETTER
     * Heading text to be displayed on the step. May be null.
     */
    @JsonGetter("heading")
    public String getHeading ( ) { 
        return this.heading;
    }
    
    /** SETTER
     * Heading text to be displayed on the step. May be null.
     */
    @JsonSetter("heading")
    public void setHeading (String value) { 
        this.heading = value;
    }
 
}
