/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;

public class SurveyStateSummaryDTOBuilder {
    //the instance to build
    private SurveyStateSummaryDTO surveyStateSummaryDTO;

    /**
     * Default constructor to initialize the instance
     */
    public SurveyStateSummaryDTOBuilder() {
        surveyStateSummaryDTO = new SurveyStateSummaryDTO();
    }

    /**
     * Indicates whether and end-user has finished the survey.
     */
    public SurveyStateSummaryDTOBuilder finished(Boolean finished) {
        surveyStateSummaryDTO.setFinished(finished);
        return this;
    }

    /**
     * Represents the state of a section in a survey submission.
     */
    public SurveyStateSummaryDTOBuilder currentSection(SectionStateDTO currentSection) {
        surveyStateSummaryDTO.setCurrentSection(currentSection);
        return this;
    }

    /**
     * Represents the state of a step in a survey submission.
     */
    public SurveyStateSummaryDTOBuilder currentStep(StepStateDTO currentStep) {
        surveyStateSummaryDTO.setCurrentStep(currentStep);
        return this;
    }

    /**
     * An estimate of how many steps are remaining in the survey. This is a worst-case estimate, and will generally
     * shorten as an end-user makes choices which skip subsequent parts of the survey.
     */
    public SurveyStateSummaryDTOBuilder stepsRemaining(Integer stepsRemaining) {
        surveyStateSummaryDTO.setStepsRemaining(stepsRemaining);
        return this;
    }

    /**
     * Collection of currently completed sections, and their completed steps Ids.
     */
    public SurveyStateSummaryDTOBuilder completedSections(LinkedHashMap<String, Object> completedSections) {
        surveyStateSummaryDTO.setCompletedSections(completedSections);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SurveyStateSummaryDTO build() {
        return surveyStateSummaryDTO;
    }
}