/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class SurveyStateSummaryDTO 
        implements java.io.Serializable {
    private static final long serialVersionUID = 2252202987450519777L;
    private String sessionId;
    private Boolean finished;
    private SectionStateDTO currentSection;
    private StepStateDTO currentStep;
    private Integer stepsRemaining;
    private LinkedHashMap<String, Object> completedSections;

    /** GETTER
     * Session id associate with the user survey interaction.
     */
    @JsonGetter("sessionId")
    public String getSessionId ( ) {
        return this.sessionId;
    }

    /** SETTER
     * Session id associate with the user survey interaction.
     */
    @JsonSetter("sessionId")
    public void setSessionId (String value) {
        this.sessionId = value;
    }

    /** GETTER
     * Indicates whether and end-user has finished the survey.
     */
    @JsonGetter("finished")
    public Boolean getFinished ( ) { 
        return this.finished;
    }
    
    /** SETTER
     * Indicates whether and end-user has finished the survey.
     */
    @JsonSetter("finished")
    public void setFinished (Boolean value) { 
        this.finished = value;
    }
 
    /** GETTER
     * Represents the state of a section in a survey submission.
     */
    @JsonGetter("currentSection")
    public SectionStateDTO getCurrentSection ( ) { 
        return this.currentSection;
    }
    
    /** SETTER
     * Represents the state of a section in a survey submission.
     */
    @JsonSetter("currentSection")
    public void setCurrentSection (SectionStateDTO value) { 
        this.currentSection = value;
    }
 
    /** GETTER
     * Represents the state of a step in a survey submission.
     */
    @JsonGetter("currentStep")
    public StepStateDTO getCurrentStep ( ) { 
        return this.currentStep;
    }
    
    /** SETTER
     * Represents the state of a step in a survey submission.
     */
    @JsonSetter("currentStep")
    public void setCurrentStep (StepStateDTO value) { 
        this.currentStep = value;
    }
 
    /** GETTER
     * An estimate of how many steps are remaining in the survey. This is a worst-case estimate, and will generally
     * shorten as an end-user makes choices which skip subsequent parts of the survey.
     */
    @JsonGetter("stepsRemaining")
    public Integer getStepsRemaining ( ) { 
        return this.stepsRemaining;
    }
    
    /** SETTER
     * An estimate of how many steps are remaining in the survey. This is a worst-case estimate, and will generally
     * shorten as an end-user makes choices which skip subsequent parts of the survey.
     */
    @JsonSetter("stepsRemaining")
    public void setStepsRemaining (Integer value) { 
        this.stepsRemaining = value;
    }
 
    /** GETTER
     * Collection of currently completed sections, and their completed steps Ids.
     */
    @JsonGetter("completedSections")
    public LinkedHashMap<String, Object> getCompletedSections ( ) { 
        return this.completedSections;
    }
    
    /** SETTER
     * Collection of currently completed sections, and their completed steps Ids.
     */
    @JsonSetter("completedSections")
    public void setCompletedSections (LinkedHashMap<String, Object> value) { 
        this.completedSections = value;
    }
 
}
