/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;

public class SurveyStateDTOBuilder {
    //the instance to build
    private SurveyStateDTO surveyStateDTO;

    /**
     * Default constructor to initialize the instance
     */
    public SurveyStateDTOBuilder() {
        surveyStateDTO = new SurveyStateDTO();
    }

    /**
     * List of all sections relevant to the survey based on its state.
     */
    public SurveyStateDTOBuilder sectionStates(List<SectionStateDTO> sectionStates) {
        surveyStateDTO.setSectionStates(sectionStates);
        return this;
    }

    /**
     * List of all steps through which the session has navigated, up to the current step. When returned for an update, this
     * will contain only steps following the step for which the update was performed.
     */
    public SurveyStateDTOBuilder steps(List<StepStateDTO> steps) {
        surveyStateDTO.setSteps(steps);
        return this;
    }

    /**
     * The identifier of the current step (the step the session must complete to proceed).
     */
    public SurveyStateDTOBuilder currentStepRef(String currentStepRef) {
        surveyStateDTO.setCurrentStepRef(currentStepRef);
        return this;
    }

    /**
     * An estimate of how many steps are remaining in the survey. This is a worst-case estimate, and will generally
     * shorten as the end-user makes choices which skip subsequent parts of the survey.
     */
    public SurveyStateDTOBuilder stepsRemaining(Integer stepsRemaining) {
        surveyStateDTO.setStepsRemaining(stepsRemaining);
        return this;
    }

    /**
     * Indicates whether the session has finished the survey.
     */
    public SurveyStateDTOBuilder finished(Boolean finished) {
        surveyStateDTO.setFinished(finished);
        return this;
    }

    /**
     * List of all questions used by the survey. Only populated on survey state calls. Empty for update calls.
     */
    public SurveyStateDTOBuilder questions(List<QuestionDTO> questions) {
        surveyStateDTO.setQuestions(questions);
        return this;
    }

    /**
     * Map of all the session's answers, up to the end of the path for which the session can navigate to without performing
     * updates.
     */
    public SurveyStateDTOBuilder answers(LinkedHashMap<String, Object> answers) {
        surveyStateDTO.setAnswers(answers);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SurveyStateDTO build() {
        return surveyStateDTO;
    }
}
