/*
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.philips.ai.models;

import java.util.*;

public class UpdateSurveyStateRequestDTOBuilder {
    //the instance to build
    private UpdateSurveyStateRequestDTO updateSurveyStateRequestDTO;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateSurveyStateRequestDTOBuilder() {
        updateSurveyStateRequestDTO = new UpdateSurveyStateRequestDTO();
    }

    /**
     * The identifier of the step on which the update was performed. Provided answers must correspond to the question on
     * this step.
     */
    public UpdateSurveyStateRequestDTOBuilder stepRef(String stepRef) {
        updateSurveyStateRequestDTO.setStepRef(stepRef);
        return this;
    }

    /**
     * Map of answers for the question on the referenced step. Answers are keyed by question identifier.
     */
    public UpdateSurveyStateRequestDTOBuilder answers(LinkedHashMap<String, Object> answers) {
        updateSurveyStateRequestDTO.setAnswers(answers);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateSurveyStateRequestDTO build() {
        return updateSurveyStateRequestDTO;
    }
}
