/**
 * SmartSleepAnalyzer
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of QuestionsDTO
 */
class QuestionsDTO extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.answersTemplate = this.constructor.getValue(obj.answersTemplate);
        this.heading = this.constructor.getValue(obj.heading);
        this.questions = this.constructor.getValue(obj.questions);
        this.updateAnswersTemplate = this.constructor.getValue(obj.updateAnswersTemplate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'answersTemplate', realName: 'answersTemplate' },
            { name: 'heading', realName: 'heading' },
            { name: 'questions', realName: 'questions', array: true, type: 'QuestionDTO' },
            {
                name: 'updateAnswersTemplate',
                realName: 'updateAnswersTemplate',
                type: 'UpdateSurveyStateRequestDTO',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = QuestionsDTO;
